version: '3.7'

services:
  php-from-scratch:
    image: webdevops/php-nginx:8.1
    container_name: php-from-scratch
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app/public
      - PHP_DISPLAY_ERRORS=0
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=500M
      - PHP_DEBUGGER="xdebug"
      # xdebug v3
      # export PHP_IDE_CONFIG="serverName=_"
      - XDEBUG_MODE=debug
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9090
    ports:
      - "8080:80"
